# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ task4 ]
  pull_request:
    branches: [ task4 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      GOOGLE_TEST_DIR: googletest/googletest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it -DBUILD_SHARED_LIBS=ON -Dgtest_build_samples=ON 
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build
      run: |
        cd task4
        mkdir 3rdparty
        cd 3rdparty/
        git clone https://github.com/google/googletest.git
        cd ../
        mkdir build && cd build/
        cmake -DCMAKE_INSTALL_PREFIX:PATH=../ ..
        make
        make install
        cd ..
        mkdir Distributive
        cp -r exe/* Distributive/

    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: bin/CTestExe
        report-path: report.xml
        working-directory: task4/

    - name: UploadArtifacts
      uses: actions/checkout@v2
      with:
        name: Distributive
        path: task4/Distributive
        
